name: Quality control

#only run on push on master if a python source file
#in the "src" dir is changed

on: 
  push:
    branches: 
      - master
    paths:
      - "src/*.py"
  pull_request:
    paths:
      - "src/*.py"

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      #cache pip dependencies, will update if requirements.txt changes
      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Tools
        run: pip install pytest black flake8 mypy
      
      - name: Test
        working-directory: "./src"
        run: pytest
      
      - name: Autoformat
        uses: samuelmeuli/lint-action@v1
        with:
          auto_fix: true
          github_token: ${{ secrets.github_token }}
          black_dir: "./src"
          black_args: "*"

      - name: Lint
        uses: samuelmeuli/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          # Enable linters
          mypy_dir: "./src"
          mypy_args: "--ignore-missing-stubs=numpy,scipy,scipy.optimise,matplotlib,matplotlib.pyplot *"
          mypy: true

          flake8_dir: "./src"
          flake8_args: "--ignore=E501,E302"
          flake8: true
